name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include: 
      - main
      - dev
      - release/*
      - hotfix/*
      - support/*
  tags:
    include:
      - release-*

parameters:
  - name: cache_nuget
    displayName: Cache NuGet packages
    type: boolean
    default: false

variables:
  nodeVersion: 18.x
  solution: Umbraco.Commerce.ProductFeeds.sln
  buildConfiguration: Release
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

stages: 
  - stage: Build
    variables:
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    jobs:
      - job: Build
        pool: 
          vmImage: ubuntu-latest
        steps:
          # Checkout source (avoid shallow clone to calculate version height)
          - checkout: self
            fetchDepth: 0

          # Setup build environment
          - task: NuGetAuthenticate@1
            displayName: Authenticate NuGet

          - task: UseDotNet@2
            displayName: Use .NET SDK from global.json
            inputs:
              useGlobalJson: true

          # Cache and restore NuGet packages
          - task: Cache@2
            condition: ${{ parameters.cache_nuget }}
            displayName: Cache NuGet packages
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/packages.lock.json, !**/bin/**, !**/obj/**'
              restoreKeys: |
                nuget | "$(Agent.OS)"
                nuget
              path: $(NUGET_PACKAGES)

          - script: dotnet restore $(solution) --locked-mode
            displayName: Restore NuGet packages
          
          # Build frontend
          - task: NodeTool@0
            displayName: 'Install nodejs 20.x'
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'

          - task: CmdLine@2
            displayName: 'Build frontend'
            inputs:
              workingDirectory: $(Build.SourcesDirectory)/src/Umbraco.Commerce.ProductFeeds.Client/frontend
              script: |
                npm i
                npm run build

          # Build
          - script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore -p:ContinuousIntegrationBuild=true
            displayName: Run dotnet build

          - task: DotNetCoreCLI@2
            displayName: 'Running tests'
            inputs:
              command: 'test'

          # Pack
          - script: dotnet pack $(solution) --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/nupkg
            displayName: Run dotnet pack

          # Publish
          - task: PublishPipelineArtifact@1
            displayName: Publish NuGet packages
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/nupkg
              artifactName: nupkg


          - task: PublishPipelineArtifact@1
            displayName: Publish build output
            inputs:
              targetPath: $(Build.SourcesDirectory)/src
              artifactName: build_output
